name: "Feature request"
description: Propose a new capability
labels: ["type:feature", "status:triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      placeholder: What’s the underlying need?
    validations:
      required: true
  - type: textarea
    id: user_story
    attributes:
      label: User story
      placeholder: As a <role>, I want <capability> so that <benefit>.
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of verifiable outcomes.
      placeholder: "- [ ] …"
    validations:
      required: false
  - type: input
    id: scope
    attributes:
      label: Out of scope (optional)
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["P0", "P1", "P2"]
    validations:
      required: true
  - type: input
    id: area
    attributes:
      label: Area / Component (label)
      placeholder: e.g., area:search
